# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-23 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_DefaultBuyPriceIzZero'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='not_used_notification_sent_to_student',
            field=models.BooleanField(default=False),
        ),
    ]
